## Anurag Kumar
## 419MA5074

In [1]:
import numpy as np

In [6]:
A = np.array([[6,-2,2,4],[12,-4,6,10],[3,-13,9,3],[-6,4,1,-18]])
A

array([[  6,  -2,   2,   4],
       [ 12,  -4,   6,  10],
       [  3, -13,   9,   3],
       [ -6,   4,   1, -18]])

In [8]:
b = np.array([16, 30, -19, -34])
b

array([ 16,  30, -19, -34])

In [17]:
# Question 1(a)

n = len(b)
n
for k in range (n-1):
    max_row_index = np.argmax(abs(A[k:n,k]))+k
    A[[k,max_row_index]] = A[[max_row_index,k]]
    b[[k,max_row_index]] = b[[max_row_index,k]]
    
    for i in range(k+1,n,1):
        mult = A[i,k]/A[k,k]
        for j in range(k,n,1):
            A[i,j] = A[i,j]-mult*A[k,j]
        b[i] = b[i]-mult*b[k]
x = np.zeros(n)
x[n-1] = b[n-1]/A[n-1,n-1]
for i in range(n-2,-1,-1):
    sum = b[i]
    for j in range(i+1,n,1):
        sum = sum -A[i,j]*x[j]
    x[i] = sum/A[i,i]
print(x)

[ 3.  1. -2.  1.]


In [18]:
# Question 1(b)

for k in range(n):
    for i in range(n):
        if i!=k:
            mult = A[i,k]/A[k,k]
            for j in range(k,n):
                A[i,j] = A[i,j] - mult*A[k,j]
            b[i] = b[i] - mult*b[k]
c = np.zeros(n)
for i in range(n):
    c[i] = b[i]/A[i,i]
print('Answer')
print(c)

Answer
[ 2.83333333  1.         -2.          1.        ]


In [19]:
# Question 1(c)

n = A.shape[0]
L = np.zeros([n,n])
P = np.identity(n)
for k in range(n-1):
    max_row_index = np.argmax(abs(A[k:n,k]))+k
    A[[k,max_row_index]] = A[[max_row_index,k]]
    P[[k,max_row_index]] = P[[max_row_index,k]]
    L[[k,max_row_index]] = L[[max_row_index,k]]
    for i in range(k+1,n,1):
        mult = A[i,k]/A[k,k]
        L[i,k] = mult
        for j in range(k,n,1):
            A[i,j] = A[i,j]-mult*A[k,j]
U=A
for i in range(n):
    L[i,i]=1
print(L)
print(U)
print(P)
print(np.dot(L,U))
print(np.dot(P,A))

[[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0. -0.  1.  0.]
 [ 0. -0.  0.  1.]]
[[ 12   0   0   0]
 [  0 -12   0   0]
 [  0   0   5   0]
 [  0   0   0  -3]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[ 12.   0.   0.   0.]
 [  0. -12.   0.   0.]
 [  0.   0.   5.   0.]
 [  0.   0.   0.  -3.]]
[[ 12.   0.   0.   0.]
 [  0. -12.   0.   0.]
 [  0.   0.   5.   0.]
 [  0.   0.   0.  -3.]]
